---
- hosts: all
  vars:
    
    # Brew packages to be installed
    brew_packages:
      - ansible
      - autoconf
      - automake
      - awscli
      - bat
      - coreutils
      - ctop
      - findutils
      - fluxctl
      - fzf
      - gnupg
      - gnutls
      - htop
      - hub
      - imagemagick
      - jq
      - kubernetes-cli
      - kubernetes-helm
      - node
      - npm
      - ntfs-3g
      - openssl
      - pinentry
      - prettyping
      - rcm
      - shpotify
      - socat
      - terraform
      - thefuck
      - tldr
      - vagrant
      - vagrant-manager
      - wget
      - zsh
      - zsh-autosuggestions
      - zsh-history-substring-search
      - zsh-syntax-highlighting

    # Brew cask packages to be installed
    brew_cask_packages:
      - authy
      - bitwarden
      - brave-browser
      - clipy
      - cyberduck
      - docker
      - firefox
      - font-hack-nerd-font
      - google-chrome
      - google-cloud-sdk
      - gpg-suite
      - iterm2
      - karabiner-elements
      - keybase
      - minikube
      - osxfuse
      - slack
      - spotify
      - virtualbox
      - virtualbox-extension-pack
      - visual-studio-code
      - vlc
    
    # npm packages to be installed globally
    npm_packages:
      - serverless
      - vtop

    # Brew packages to be uninstalled
    brew_packages_uninstall:
      - cowsay # Feel free to change this, it's just an example

    # Brew cask packages to be uninstalled
    brew_cask_packages_uninstall:
      - dropbox #  Feel free to change this, it's just an example

    # Taps to be tapped
    taps:
      - thoughtbot/formulae # rcm
      - caskroom/fonts # font-hack-nerd-fonts

    dotfile_repo_username: nille # the GH repo where your dotfiles are
    
    install_oh_my_zsh:  true
    
    zsh_path: /usr/local/bin/zsh

    home: "{{ lookup('env','HOME') }}"

  tasks:

    ### Homebrew 

  # Tap those taps
  - homebrew_tap:
      name: "{{ item }}"
    loop: "{{ taps }}"

  # Install brew cask packages
  - homebrew_cask:
      name: "{{ item }}"
      state: present
    loop: "{{ brew_cask_packages }}"

  # Install brew packages
  - homebrew:
      name: "{{ item }}"
      state: present
    loop: "{{ brew_packages }}"

  # Uninstall brew packages
  - homebrew:
      name: "{{ item }}"
      state: absent
    loop: "{{ brew_packages_uninstall }}"

  # Uninstall brew cask packages
  - homebrew_cask:
      name: "{{ item }}"
      state: absent
    loop: "{{ brew_cask_packages_uninstall }}"

  # Make sure everything brew is up to date
  - name: Update everything brew
    shell: brew update && brew upgrade

  # Cleanup after homebrew
  - name: Cleanup after brewing
    shell: brew cleanup

    ### Node modules

  # Install npm packages
  - name: Install npm packages
    npm:
      name: "{{ item }}"
      path: /usr/local/bin
    loop: "{{ npm_packages }}"

    ### ZSH radness 

  - name: Determine if zsh is default/current shell
    shell: echo $SHELL
    register: current_shell

  - name: Enable zsh in /etc/shells
    shell: sudo /bin/sh -c 'grep -q "{{ zsh_path }}" /etc/shells || echo "{{ zsh_path }}" >> /etc/shells'
    when: current_shell.stdout != '/usr/local/bin/zsh'    
    #" unbreak my syntax highlighting...

  - name: Set zsh as default shell
    shell: chsh -s {{ zsh_path }}
    when: current_shell.stdout != '/usr/local/bin/zsh'
    sudo: true

  - name: Use GNU tools instead of osx counterparts (grep find etc) 
    shell: echo 'export PATH=$(brew --prefix coreutils)/libexec/gnubin:$PATH' >> ~/.zshrc


  - name: Install oh-my-zsh
    git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh
    sudo: false
    when: install_oh_my_zsh == true
    tags: install_oh_my_zsh

    ### House cleaning

  # Create the locate database
  - name: Create the locate database
    shell: sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist