---
- hosts: all
  vars:
    
    # Brew packages to be installed
    brew_packages:
      - ansible
      - autoconf
      - automake
      - awscli
      - bat
      - ctop
      - fluxctl
      - fzf
      - gnupg
      - gnutls
      - htop
      - hub
      - imagemagick
      - jq
      - kubernetes-cli
      - kubernetes-helm
      - node
      - npm
      - ntfs-3g
      - openssl
      - pinentry
      - prettyping
      - rcm
      - shpotify
      - socat
      - terraform
      - thefuck
      - tldr
      - wget
      - zsh
      - zsh-autosuggestions
      - zsh-history-substring-search
      - zsh-syntax-highlighting

    # Brew cask packages to be installed
    brew_cask_packages:
      - authy
      - bitwarden
      - brave-browser
      - clipy
      - cyberduck
      - docker
      - firefox
      - font-hack-nerd-fonts
      - google-chrome
      - google-cloud-sdk
      - gpg-suite
      - iterm2
      - karabiner-elements
      - keybase
      - minikube
      - osxfuse
      - slack
      - spotify
      - visual-studio-code
      - vlc

    # Brew packages to be uninstalled
    brew_packages_uninstall:
      - cowsay # Feel free to change this, it's just an example

    # Brew cask packages to be uninstalled
    brew_cask_packages_uninstall:
      - dropbox #  Feel free to change this, it's just an example

    # Taps to be tapped
    taps:
      - thoughtbot/formulae # rcm
      - caskroom/fonts # font-hack-nerd-fonts

  tasks:

  # Tap those taps
  - homebrew_tap:
      name: "{{ item }}"
    loop: "{{ taps }}"

  # Install brew cask packages
  - homebrew_cask:
      name: "{{ item }}"
      state: present
    loop: "{{ brew_cask_packages }}"

  # Install brew packages
  - homebrew:
      name: "{{ item }}"
      state: present
    loop: "{{ brew_packages }}"

  # Uninstall brew packages
  - homebrew:
      name: "{{ item }}"
      state: absent
    loop: "{{ brew_packages_uninstall }}"

  # Uninstall brew cask packages
  - homebrew_cask:
      name: "{{ item }}"
      state: absent
    loop: "{{ brew_cask_packages_uninstall }}"

  # Make sure everything brew is up to date
  - name: Update everything brew
    shell: brew update && brew upgrade

  # Cleanup after homebrew
  - name: Cleanup after brewing
    shell: brew cleanup

  # Install npm packages
  - name: Install packages based on package.json.
    npm:
      path: /usr/local/bin

  # Update npm packages
  - name: Update packages based on package.json to their latest version.
    npm:
      path: /usr/local/bin
      state: latest